name: Prepare
description: Install dependencies and build the project
inputs:
  build:
    description: Build the production bundle of the platform
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      id: pnpm-install
      with:
        run_install: false
    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Install dependencies
      shell: bash
      run: pnpm install
    - name: Build
      if: inputs.build == 'true'
      shell: bash
      run: pnpm run build
      env:
        npm_config_workspace_concurrency: '1'
